#ClientWorker.js.org
name: XlencoのClientWorker
cleaninterval: 1000*20 #每20秒检测并清理一次缓存
catch_rules: 
        - search: \/([^\/.]+)\/post \/([^\/.]+)$ #匹配/path，跳为/path.html
          action: redirect
          redirect: 
            to: $1/p
            status: 301
        - search: (^4|^5) 
          searchin: status 
          action: return
          return:
            body: The GateWay is down!This Page is provided by ClientWorker!
            status: 503
