#ClientWorker.js.org
name: XlencoのClientWorker 
cleaninterval: 1000*20 #每20秒检测并清理一次缓存
catch_rules: 
#静态资源 CDN 选择
    - rule: ^https\:\/\/((cdn|test1|quantil|fastly|gcore)\.jsdelivr\.net\/npm|unpkg\.com|unpkg\.onmicrosoft\.cn)
      transform_rules:
        - search: _
          replace:
            - _ 
            - https://jsd.onmicrosoft.cn/npm
            - https://npm.onmicrosoft.cn
            - https://cdn.cnortles.top/npm
            - https://unpkg.cnortles.top   
            - https://jsd.cky.codes/npm   
            - https://npm.elemecdn.com
            - https://npm.sourcegcdn.com  
            - https://cdn.staticfile.org
            - https://cdn.qystu.cc/npm
            - https://cdn.moezz.cn/npm
            - https://cdn.xxhzm.cn/proxy/npm
            - https://shadow.elemecdn.com/npm
            - https://jsd.iftft.com/npm
            - https://cdn.chuqis.com/npm
            - https://jsd.cdn.tubo.net.cn/npm
            - https://s.cky.qystu.cc/npm
          action: fetch
          fetch:
            status: 200
            engine: parallel
            preflight: false # false
            timeout: 3000
            cache:
              expire: 1000*60*60*12 
              delay: 300
#github加速
    - rule: ^https\:\/\/((cdn|fastly|gcore|test1|quantil)\.jsdelivr\.net\/gh|jsd\.onmicrosoft\.cn\/gh)
      transform_rules:
        - search: _
          replace:
            - _
            - https://jsd.onmicrosoft.cn/gh
            - https://cdn.cnortles.top/gh
            - https://jsd.cky.codes/gh
            - https://assets.tnxg.whitenuo.cn/proxy/gh
            - https://cdn.qystu.cc/gh
            - https://cdn.moezz.cn/gh
            - https://cdn.xxhzm.cn/proxy/gh
            - https://shadow.elemecdn.com/gh
            - https://jsd.iftft.com/gh
            - https://cdn.chuqis.com/gh
            - https://jsd.cdn.tubo.net.cn/gh
            - https://s.cky.qystu.cc/gh 
          action: fetch
          fetch:
            status: 200
            engine: parallel
            preflight: false # false
            timeout: 30000
            cache:
              expire: 1000*60*60*12 
              delay: 300
#第三方api图片缓存
    - rule: ^https\:\/\/(xlenco\.onmicrosoft\.cn\/(.*)\.(jpg|webp)$|preview\.cloud\.189\.cn\/(.*))
      transform_rules:
        - search: _
          action: fetch
          fetch:
            status: 200
            engine: fetch
            preflight: false
            timeout: 30000
            cache:
              enable: true
              expire: 1000*60*60*12*365
#匹配B站资源链接
    - rule: ^(http|https)\:\/\/(i0|i1|i2|i3)\.hdslb\.com 
      transform_rules:
        - search: _ #多cdn并发
          replace:
            - https://s1.hdslb.com
            - https://s2.hdslb.com
            - https://s3.hdslb.com
          action: fetch
          fetch:
            engine: parallel
            status: 200
            preflight: false
            timeout: 30000
            delay: 4000
#字体缓存
    - rule: ^https\:\/\/((s1|s2|s3).hdslb.com\/bfs\/static\/jinkela\/long\/font\/HarmonyOS_Regular\.(.*)\.woff2$|gstatic\.loli.net\/s\/firacode\/v21\/(.*)\.woff2$)
      transform_rules:
        - search: _
          action: fetch
          fetch:
            status: 200
            engine: fetch
            preflight: false
            threads: 5
            timeout: 30000
            cache:
              enable: true
              expire: 1000*60*60*2
